default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: rails-grape
  password: rails-grape-123
  pool: 5

development:
  <<: *default
  database: rails-grape_development

test:
  <<: *default
  database: rails-grape_test
